[general]
start_url = "gemini://tilde.black"

[colors]
    h1 = "#08F6F8"
    h2 = "#FF79D9"
    h3 = "#FEFE55"
    list = "#FEFDFE"
    text = "#FEFDFE"
    background = "#340F2F"

[characters]
h1 = "★ "
h2 = "★ "
h3 = "★ "
list = "• "

[monospace]
gemini=false
gopher=true
finger=true
