[general]
start_url = "gemini://tilde.black"

[colors]
h1 = "#34e5eb"
h2 = "#ebd534"
h3 = "chartreuse"
list = "#C71585"
text = "#e9e9e9"
background = "#333333"

[characters]
h1 = "★ "
h2 = "★ "
h3 = "★ "
list = "• "

[monospace]
gemini=false
gopher=true
finger=true
